FROM scratch
ADD .docker/alpine.tar.gz /
RUN apk add --no-cache nginx \
    && addgroup -S -g 10001 app \
    && adduser -S -D -H -u 10001 -G app app

COPY web/nginx.conf /etc/nginx/nginx.conf
COPY --chown=10001:10001 web/index.html /var/www/html/index.html
USER 10001:10001

EXPOSE 8080
STOPSIGNAL SIGQUIT
ENTRYPOINT ["nginx", "-e", "/dev/stderr"]
CMD ["-g", "daemon off;"]
